# This code is for a single view of an existing dashboard.
  - theme: Backend-selected
    title: Baby
    path: baby
    icon: mdi:baby-carriage
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: vertical-stack
            cards:
              - type: custom:card-templater
                entities:
                  - sensor.pregnancy
                card:
                  type: picture-elements
                  image_template: >-
                    {{ states.sensor.pregnancy.attributes.fetus_size_fruit_image
                    }}
                  tap_action:
                    action: toggle
                  elements:
                    - type: state-label
                      entity: sensor.pregnancy
                      attribute: trimester
                      suffix: ' Trimester'
                      style:
                        font-size: 20px
                        font-style: italic
                        top: 4%
                        left: 50%
                    - type: state-label
                      entity: sensor.pregnancy
                      prefix: 'It''s Week '
                      suffix: '!'
                      style:
                        font-size: 40px
                        top: 12%
                        left: 50%
                    - type: state-label
                      entity: sensor.pregnancy
                      prefix: '(Day '
                      attribute: day_in_week
                      suffix: )
                      style:
                        font-size: 20px
                        top: 20%
                        left: 50%
                    - type: custom:text-action-element
                      text: The fetus is about
                      style:
                        font-size: 16px
                        top: 90%
                        left: 50%
                    - type: state-label
                      entity: sensor.pregnancy
                      prefix: 'the size of '
                      attribute: fetus_size_fruit
                      suffix: '!'
                      style:
                        font-size: 16px
                        top: 95%
                        left: 50%
          - type: gauge
            name: Baby Download Status
            entity: sensor.pregnancy_percent
            min: 0
            max: 100
            severity:
              green: 66
              yellow: 33
              red: 0
            needle: true
            unit: '%'
          - type: markdown
            content: >
              ## Read about week {{ states.sensor.pregnancy.state }} on:

              * [BabyCenter]({{
              states.sensor.pregnancy.attributes.babycenter_link }})
              
              * [What To Expect]({{
              states.sensor.pregnancy.attributes.what_to_expect_link }})

              * [Verywell Family]({{
              states.sensor.pregnancy.attributes.verywellfamily_link }})

              * [Mayo Clinic]({{
              states.sensor.pregnancy.attributes.mayo_clinic_link }})

              * [Manly]({{ states.sensor.pregnancy.attributes.manly_link }})

              * [Geeky]({{ states.sensor.pregnancy.attributes.geeky_link }})

              * [Cravings]({{ states.sensor.pregnancy.attributes.cravings_link
              }})
      - type: vertical-stack
        cards:
          - type: picture
            image: /local/ultrasound_week_8.jpeg
            tap_action:
              action: none
            hold_action:
              action: none
          - type: markdown
            content: >
              ## Week {{ states.sensor.pregnancy.state }} Developmental
              Milestones:

              {{ states.sensor.pregnancy.attributes.fetal_development }}
          - type: entities
            entities:
              - entity: sensor.pregnancy_next_check
                icon: mdi:stethoscope
                name: Next Checkup
              - entity: sensor.pregnancy_due_date
                name: Due date
              - entity: sensor.pregnancy_days
                icon: mdi:arrow-left-circle-outline
              - entity: sensor.pregnancy_days_left
                icon: mdi:arrow-right-circle-outline
              - entity: sensor.pregnancy_fetal_length
                icon: mdi:ruler
              - entity: sensor.pregnancy_fetal_weight
                icon: mdi:weight
            title: Data
      - type: vertical-stack
        cards:
          - type: custom:card-templater
            entities:
              - sensor.pregnancy
            card:
              type: picture-elements
              image_template: '{{ states.sensor.pregnancy.attributes.fetus_size_manly_image }}'
              elements:
                - type: state-label
                  entity: sensor.pregnancy
                  attribute: trimester
                  suffix: ' Trimester'
                  style:
                    font-size: 20px
                    font-style: italic
                    top: 8%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: 'It''s Week '
                  suffix: '!'
                  style:
                    font-size: 40px
                    top: 20%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: '(Day '
                  attribute: day_in_week
                  suffix: )
                  style:
                    font-size: 20px
                    top: 32%
                    left: 50%
                - type: custom:text-action-element
                  text: The fetus is about
                  style:
                    font-size: 16px
                    top: 85%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: 'the size of '
                  suffix: '!'
                  attribute: fetus_size_manly
                  style:
                    font-size: 16px
                    top: 93%
                    left: 50%
          - type: custom:card-templater
            entities:
              - sensor.pregnancy
            card:
              type: picture-elements
              image_template: '{{ states.sensor.pregnancy.attributes.fetus_size_geeky_image }}'
              elements:
                - type: state-label
                  entity: sensor.pregnancy
                  attribute: trimester
                  suffix: ' Trimester'
                  style:
                    font-size: 20px
                    font-style: italic
                    top: 8%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: 'It''s Week '
                  suffix: '!'
                  style:
                    font-size: 40px
                    top: 20%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: '(Day '
                  attribute: day_in_week
                  suffix: )
                  style:
                    font-size: 20px
                    top: 32%
                    left: 50%
                - type: custom:text-action-element
                  text: The fetus is about
                  style:
                    font-size: 16px
                    top: 85%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: 'the size of '
                  suffix: '!'
                  attribute: fetus_size_geeky
                  style:
                    font-size: 16px
                    top: 93%
                    left: 50%
          - type: custom:card-templater
            entities:
              - sensor.pregnancy
            card:
              type: picture-elements
              image_template: >-
                {{ states.sensor.pregnancy.attributes.fetus_size_cravings_image
                }}
              elements:
                - type: state-label
                  entity: sensor.pregnancy
                  attribute: trimester
                  suffix: ' Trimester'
                  style:
                    font-size: 20px
                    font-style: italic
                    top: 8%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: 'It''s Week '
                  suffix: '!'
                  style:
                    font-size: 40px
                    top: 20%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: '(Day '
                  attribute: day_in_week
                  suffix: )
                  style:
                    font-size: 20px
                    top: 32%
                    left: 50%
                - type: custom:text-action-element
                  text: The fetus is about
                  style:
                    font-size: 16px
                    top: 85%
                    left: 50%
                - type: state-label
                  entity: sensor.pregnancy
                  prefix: 'the size of '
                  suffix: '!'
                  attribute: fetus_size_cravings
                  style:
                    font-size: 16px
                    top: 93%
                    left: 50%
